BoxLayout:
    orientation: "vertical"
    Button:
        text: "Clear"
        on_press: app.handle_clear()
        font_size: 24
    TextInput:
        id: input_name
        text: ""
        multiline: False
        font_size: 24
    Button:
        text: "Greet"
        on_press: app.handle_greet()
        font_size: 24
    Label:
        id: output_label
        text: "Enter your name"
        color: (1, 1, 0, 1)
        font_size: 24
